'use strict';

export const AUTHORIZATION_STORE = 'AUTHORIZATION_STORE';
export const DASHBOARD_STORE = 'DASHBOARD_STORE';
export const QUESTIONS_LIST_STORE = 'QUESTIONS_LIST_STORE';
export const QUESTIONS_ITEM_STORE = 'QUESTIONS_ITEM_STORE';
